---

- name: GET gitlab
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash


- name: install gitlab ce
  yum: pkg=gitlab-ce state=present

- name: gitlab reconfigure
  shell: gitlab-ctl reconfigure
